In [42]:
import numpy as np 
from numpy.polynomial import Polynomial

z = [Polynomial([-i/100,1]) for i in range(100,125,5)]
for i in range(1, len(z)):
    z[i] = z[i]*z[i-1]

# fd = [0.47186, -0.2414, 0.012, 0.01335, -0.1066]
fd =[0.37678, -0.2332,0.02267,0.01335, -0.1066]
a = 0.682689 + sum([fd[i]*z[i] for i in range(5)])
print (a, "Interpolated value = ", a(1.235))

0.22250702750000007 + 0.08807409749999984·x¹ + 1.2023203749999998·x² -
1.3232624999999998·x³ + 0.59965·x⁴ - 0.1066·x⁵ Interpolated value =  0.7612317817483868


In [41]:
import numpy as np 
from numpy.polynomial import Polynomial

def polb(h,target,n):
    uo = u = -0.3
    ua = [1]

    for j in range(1,len(fd)):
        ua.append(u)
        print((uo + j*1))
        u *= (uo + j*1)

    ua = np.array(ua)
    for i in range(len(ua)):
        ua[i] /= np.math.factorial(i)

    return (ua)

h = 0.05

polb(h, 1.235, 10)

0.7
1.7
2.7
3.7
4.7
[ 1.         -0.3        -0.105      -0.0595     -0.0401625  -0.02972025]
[0.7887, -0.113034, 0.024486, -0.00134886, -0.00053617, 0.00316818]
0.70143515


In [55]:
def _poly_newton_coefficient(x, y):
    """
    x: list or np array contanining x data points
    y: list or np array contanining y data points
    """

    m = len(x)

    x = np.copy(x)
    a = np.copy(y)
    for k in range(1, m):
        a[k:m] = (a[k:m] - a[k - 1])/(x[k:m] - x[k - 1])

    return a

def newton_polynomial(x_data, y_data, x):
    """
    x_data: data points at x
    y_data: data points at y
    x: evaluation point(s)
    """
    a = _poly_newton_coefficient(x_data, y_data)
    print (a)
    n = len(x_data) - 1  # Degree of polynomial
    print (n)
    p = a[n]
    print (p)

    for k in range(1, n + 1):
        print (k, a[n-k], x, x_data[n-k])
        p = a[n - k] + (x - x_data[n - k])*p

    return p

x = [i/100 for i in range(100,130,5)]
y = [0.682689, 0.706282,0.728668, 0.749856, 0.769861, 0.7887]
newton_polynomial(x, y, 1.235)

def polb(h,target,n):
    uo = u = -0.3
    ua = [1]

    for j in range(1,len(fd)+1):
        ua.append(u)
        u *= (uo + j*0.05)

    ua = np.array(ua)
    for i in range(len(ua)):
        ua[i] /= np.math.factorial(i)

    return (ua)

a = _poly_newton_coefficient(x, y)
print (a)
b = polb(h, 1,2)
print (b)
ans = 0
for i in range(len(a)):
    print (a[i]*b[i])
    ans += a[i]*b[i]
print (ans)

for i in range(len(x)):
    print (x[i], y[i])


[ 0.682689    0.47186    -0.2414      0.012       0.04       -0.10666667]
5
-0.10666666666417958
1 0.03999999999937335 1.235 1.2
2 0.012000000000012044 1.235 1.15
3 -0.2413999999999903 1.235 1.1
4 0.47185999999999906 1.235 1.05
5 0.682689 1.235 1.0
[ 0.682689    0.47186    -0.2414      0.012       0.04       -0.10666667]
[ 1.000e+00 -3.000e-01  3.750e-02 -2.500e-03  9.375e-05 -1.875e-06]
0.682689
-0.1415579999999997
-0.009052499999999635
-3.0000000000030108e-05
3.74999999994125e-06
1.9999999999533657e-07
0.5320524500000005
1.0 0.682689
1.05 0.706282
1.1 0.728668
1.15 0.749856
1.2 0.769861
1.25 0.7887


In [110]:
import numpy
h = 1/6
start = 0
end = 1
points = [start]

for j in range(200):
    points.append(points[-1]+h)
    if points[-1]+h > end:
        break
    
print (points, h)
f = lambda x: np.exp(-(x**2))
value = 0
values = [f(a) for a in points]
f0 = values[0]+values[-1]
feven = 0 
fodd = 0

# values[0] = values[-1] = 0
print (values)
for i in range(len(points)):
    if i%2 == 0:
        feven = values[i]
    else:
        fodd = values[i]

(h/3)*((1.0 + 0.3678794411714424)+4*(0.9726044771163483+0.7788007830714049+0.49935178859927626)+2*(0.8948393168143698+0.6411803884299546))


[0, 0.16666666666666666, 0.3333333333333333, 0.5, 0.6666666666666666, 0.8333333333333333, 0.9999999999999999] 0.16666666666666666
[1.0, 0.9726044771163483, 0.8948393168143698, 0.7788007830714049, 0.6411803884299546, 0.49935178859927626, 0.3678794411714424]


0.746830391489345

In [208]:
h = np.pi/12
a = 0
points = []
n = -1
while a <= np.pi/2:
    points.append(np.sin(a))
    a += h
    n += 1

print (points, n)

(h/2)*(points[0]+points[-1]+2*(sum(points[1:-1]))), 1.9885/2

[0.0, 0.06698729810778066, 0.24999999999999994, 0.4999999999999999, 0.7499999999999999, 0.9330127018922192, 1.0] 6


(0.7853981633974481, 0.99425)