# Decoder only model
The following implementation uses word embeddings using nltk tokenizer for words and tries to use the multi headed self attention model to train on text.


In [ ]:
from nltk.tokenize import sent_tokenize, word_tokenize
from tqdm import tqdm
import torch
import nltk
import torch.nn as nn
from random import randrange
import torch.nn.functional as F
nltk.download('punkt')
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print (device)
from google.colab import drive
drive.mount('/content/drive')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%%html
<style>
  table {margin-left: 0 !important;}
</style>

## Tokenizing input data

Create a mapping of the tokenized words into text and viceversa.

- load_and_encode_data_nltk

nltk uses the nltk tokenizer to split the text into sentenses and words. \
https://www.nltk.org/api/nltk.tokenize.html

- tiktoken
[todo]
- sentence piece
[todo]

In [ ]:
def read_data(filename):
    text = None
    with open(filename, "r", encoding='utf-8') as f:
        text = f.read()

    return text

In [ ]:
def load_and_encode_data_nltk(filename):
    word_to_lookup = {}
    lookup_to_word = {}
    encoded_data = []

    data = read_data(filename)
    print ('length of dataset = ', len(data))
    tokenized_data = [word_tokenize(w) for w in [s for s in sent_tokenize(data)]]
    vocabulary = set()

    for s in tokenized_data:
        for w in s:
            vocabulary.add(w)

    vocabulary = sorted(vocabulary)

    for c, i in list(zip(vocabulary, range(len(vocabulary)))):
        word_to_lookup[c] = i
        lookup_to_word[i] = c

    for s in tokenized_data:
        for w in s:
            encoded_data.append(word_to_lookup[w])

    return word_to_lookup, lookup_to_word, encoded_data

w2l, l2w, tokenized_data = load_and_encode_data_nltk("/content/drive/MyDrive/colab/pg1400.txt")

tensor_tokenized_data = torch.tensor(tokenized_data, dtype=torch.long)

length of dataset =  1013924


In [ ]:
print(tensor_tokenized_data.shape, tensor_tokenized_data.dtype)
print(tensor_tokenized_data[:100])

torch.Size([229192]) torch.int64
tensor([13697,  1241,   661,  5082,  8781,   647,   537,  1537,  5120,  7431,
         5967, 12111, 12807,  8781,  2302,  2307,  7092, 12111,  1607,  1453,
         2246,  8407,  8902,  9083,  8781, 12111, 13380,  2509,  8622,  4109,
         2246, 13322,  2188,  8622, 10315, 13172,    10,  1779,  8135,  4077,
         7440,     8,  6277,  7440,  2584,  8867,  9937,  7440, 12617, 12111,
        12069,  8781, 12111,  1241,   661,   904,  7119, 13322, 12169,  5120,
         8867,  8837,  2509, 13444,    10,   770, 13477,  2388,  8660,  7883,
         7092, 12111,  1607,  1453,     8, 13477, 13265,  6661, 12279,  3453,
        12111,  7693,  8781, 12111,  4137, 13181, 13477,  2388,  7883,  2752,
        12817, 12169,  5082,    10,  1554,    56,   647,   537,   162,    56])


## Test training dataset split

In [ ]:
n = int(0.8*len(tensor_tokenized_data))
train_data = tensor_tokenized_data[:n]
test_data = tensor_tokenized_data[n:]

In [ ]:
train_data, test_data

(tensor([13697,  1241,   661,  ...,     8,  2246, 13181]),
 tensor([12111, 11712, 12997,  ...,  8589,  5083,    10]))

In [ ]:
no_of_embeddings = 384 ## Number of trainable parameters per token.
attention_head_size = 16
batch_size = 64
block_size = 256
no_of_heads = 6
evaluation_iters = 200
total_iters = 5000
dropout = 0.2 # to prevent overfitting

train_data[:block_size+1]

tensor([13697,  1241,   661,  5082,  8781,   647,   537,  1537,  5120,  7431,
         5967, 12111, 12807,  8781,  2302,  2307,  7092, 12111,  1607,  1453,
         2246,  8407,  8902,  9083,  8781, 12111, 13380,  2509,  8622,  4109,
         2246, 13322,  2188,  8622, 10315, 13172,    10,  1779,  8135,  4077,
         7440,     8,  6277,  7440,  2584,  8867,  9937,  7440, 12617, 12111,
        12069,  8781, 12111,  1241,   661,   904,  7119, 13322, 12169,  5120,
         8867,  8837,  2509, 13444,    10,   770, 13477,  2388,  8660,  7883,
         7092, 12111,  1607,  1453,     8, 13477, 13265,  6661, 12279,  3453,
        12111,  7693,  8781, 12111,  4137, 13181, 13477,  2388,  7883,  2752,
        12817, 12169,  5082,    10,  1554,    56,   647,   537,   162,    56,
          321,   441,  1301,  4336,    56,   847,    11,     8,    36,  1785,
         5082,     1,    33,  1786,  1026,  9989, 12780,    56,  1109,    51,
            8,    40,   891,    56,   505,   395,    56,   122, 

In [ ]:
" ".join([l2w[i] for i in train_data[1:7].numpy()])

'Project Gutenberg eBook of Great Expectations'

In [ ]:
def get_data_for_processing(training_data_set):
    data = train_data if training_data_set else test_data
    sample_indices = torch.randint(len(data)-block_size, (batch_size, ))
    x = torch.stack([data[i:i+block_size] for i in sample_indices])
    y = torch.stack([data[i+1:i+block_size+1] for i in sample_indices])
    return x.to(device), y.to(device)

In [ ]:
samples_x, samples_y = get_data_for_processing(True)
for batch in range(batch_size):
    for block in range(1):
        context = samples_x[batch, :block+1]
        target = samples_y[batch, block]
        print (" ".join([l2w[i] for i in context.cpu().numpy()]), l2w[target.item()])

vocab_size = len(l2w)
print (vocab_size)

further investigation
” said
you ought
to Miss
so unassuming
in mind
excitable temperament
’ r
some suspicion
himself in
had been
Besides being
remarkable what
I lay
if I
I shall
the conduct
the mere
and I
eyes were
after hesitating
conjectures had
thing .
“ Say
his pockets
his hospitality
speckled box
Illustration ]
be possible
, and
. At
I want
scarcely see
he was
at me
therefore you
got on
, Handel
Joe ,
triumph ,
( I
helped him
something good
No ,
rather neat
, by
no idea
never was
tossing his
certainly was
was in
Hulks !
marriage ultimately
could possibly
so ,
a constraint
had told
, thinking
it ,
in his
would consent
“ Estella
Biddy .
a question
13698


In [ ]:
@torch.no_grad()
def estimation_loss():
  out = {}
  model.eval()
  for split in ['train', 'test']:
    losses = torch.zeros(evaluation_iters)
    for k in range(evaluation_iters):
      X,Y = get_data_for_processing(True if split == 'train' else False)
      logits, loss = model(X,Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out

## Attention blocks implentation.
The various classes below signify the implmenetation from various parts of the attention model for decoder.

### Self-attention head

In [ ]:
class SelfAttentionHead(nn.Module):
  def __init__(self, attention_head_size):
    super(SelfAttentionHead, self).__init__()
    self.key = nn.Linear(no_of_embeddings, attention_head_size, bias=False)
    self.query = nn.Linear(no_of_embeddings, attention_head_size, bias=False)
    self.value = nn.Linear(no_of_embeddings, attention_head_size, bias=False)
    self.dropout = nn.Dropout(dropout)
    self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
  def forward(self, idx):
    bts, bs, no_of_embeddings = idx.shape
    # print ('idx = ', idx.shape)
    k = self.key(idx)
    q = self.query(idx)

    weights = q @ k.transpose(-2,-1) * no_of_embeddings**-0.5
    # print ('w after transpose mul= ', weights.shape)
    weights = weights.masked_fill(self.tril[:bs][:bs] == 0, float('-inf'))

    weights = F.softmax(weights, dim=-1)
    weights = self.dropout(weights)

    values = self.value(idx)
    # print (weights.shape, values.shape)

    out = weights @ values

    return out

### Multi attention head

In [ ]:
class MultiHeadAttn(nn.Module):
  def __init__(self, num_heads, attention_head_size):
    super(MultiHeadAttn, self).__init__()
    self.heads = nn.ModuleList([SelfAttentionHead(attention_head_size) for _ in range(num_heads)])
    self.self_projection = nn.Linear(no_of_embeddings, no_of_embeddings)
    self.dropout = nn.Dropout(dropout)
  def forward(self, idx):
    self_attn_out = torch.cat([head(idx) for head in self.heads], dim=-1)
    return self.dropout(self.self_projection(self_attn_out))

### Feed forward


In [ ]:
class FeedForward(nn.Module):
  def __init__(self, no_of_embeddings):
    super(FeedForward, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(no_of_embeddings, 4*no_of_embeddings),
        nn.ReLU(),
        nn.Linear(4*no_of_embeddings, no_of_embeddings), # This is projection.
        nn.Dropout(dropout)
    )

  def forward(self, idx):
    return self.network(idx)

### Block
General block structure to hold other pieces

In [ ]:
class Block(nn.Module):
  def __init__(self, no_of_embeddings, no_of_heads):
    super(Block, self).__init__()
    self.self_attn_heads = MultiHeadAttn(no_of_heads, no_of_embeddings//no_of_heads)
    self.feed_forward = FeedForward(no_of_embeddings)
    self.layer_norm1 = nn.LayerNorm(no_of_embeddings)
    self.layer_norm2 = nn.LayerNorm(no_of_embeddings)

  # idx is added as a concept from residual image nets to preserve the original x input.
  def forward(self, idx):
    self_attn_heads_out = idx + self.self_attn_heads(self.layer_norm1(idx))
    ffwd_out = idx + self.feed_forward(self.layer_norm2(self_attn_heads_out))
    return ffwd_out

### Main model

In [ ]:
class LLM(nn.Module):
    def __init__(self, vocab_size, context, embedded_dim):
      super(LLM, self).__init__()
      self.embedding = nn.Embedding(vocab_size, no_of_embeddings) # batches, block_size, embeddings
      self.position_embedding = nn.Embedding(block_size, no_of_embeddings) # block_size, embeddings

      self.blocks = nn.Sequential(
          Block(no_of_embeddings, no_of_heads),
          Block(no_of_embeddings, no_of_heads),
          Block(no_of_embeddings, no_of_heads),
          Block(no_of_embeddings, no_of_heads),
          Block(no_of_embeddings, no_of_heads),
          Block(no_of_embeddings, no_of_heads),
          nn.LayerNorm(no_of_embeddings)
      )
      self.language_model_head = nn.Linear(no_of_embeddings, vocab_size)

    def forward(self, idx, targets=None):
      batch, blocksize = idx.shape
      token_embedding = self.embedding(idx)
      block_size_values = torch.arange(blocksize, device=device)
      position_embedding = self.position_embedding(block_size_values)
      tokpos_embedding = token_embedding + position_embedding
      # print (tokpos_embedding.shape, token_embedding.shape, position_embedding.shape)
      self_attn_out = self.blocks(tokpos_embedding)
      logits = self.language_model_head(self_attn_out)

      if targets is None:
          loss = None
      else:
          B,T,C = logits.shape
          logits = logits.view(B*T,C)
          targets = targets.view(B*T)
          loss = F.cross_entropy(logits, targets)

      return logits, loss

    def generate(self, idx, max_new_tokens):
      for _ in range(max_new_tokens):
          idx_condition = idx[:, -block_size:]
          # print (idx_condition)
          logits, loss = self(idx_condition)
          logits = logits[:, -1,  :]
          probs = F.softmax(logits, dim=-1)
          idx_next = torch.multinomial(probs, num_samples=1)
          idx = torch.cat((idx, idx_next), dim=1)
      return idx

model = LLM(vocab_size, block_size, vocab_size).to(device)
logits, loss = model(samples_x, samples_y)
print (logits.shape, loss)

torch.Size([16384, 13698]) tensor(9.6883, grad_fn=<NllLossBackward0>)


In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)

In [ ]:
model.summary()

### Training

In [ ]:
for step in range(total_iters):
    if step % evaluation_iters == 0:
      losses = estimation_loss()
      print("Training data loss = ", losses['train'].item(), "Test data loss = ", losses['test'].item())
    samples_x, samples_y = get_data_for_processing(True)
    logits, loss = model(samples_x, samples_y)
    optimizer.zero_grad()

    loss.backward()
    optimizer.step()


## Example generation

In [ ]:
context = torch.tensor([[w2l[i] for i in "what is the bill of the character story".split(' ')]], dtype=torch.long, device=device)
g = model.generate(context, max_new_tokens=200)
" ".join([l2w[i] for i in g.cpu().numpy()[0]])